package com.datasciencebox.serverdiscoverer.dao.server;

// Generated 26/04/2014 1:03:11 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Server generated by hbm2java
 */
public class Server implements java.io.Serializable {
	
	private String serverIpAddress;
	private String serverDomainName;
	private BigDecimal serverLattitude;
	private BigDecimal serverLongitude;
	private String serverCity;
	private String serverCountry;
	private Date dateModified;

	public Server() {
	}

	public Server(String serverIpAddress) {
		this.serverIpAddress = serverIpAddress;
	}
	
	public Server(long serverId, String serverIpAddress,
			String serverDomainName, BigDecimal serverLattitude,
			BigDecimal serverLongitude, String serverCity,
			String serverCountry, Date dateModified) {
		this.serverIpAddress = serverIpAddress;
		this.serverDomainName = serverDomainName;
		this.serverLattitude = serverLattitude;
		this.serverLongitude = serverLongitude;
		this.serverCity = serverCity;
		this.serverCountry = serverCountry;
		this.dateModified = dateModified;
	}


	public String getServerIpAddress() {
		return this.serverIpAddress;
	}

	public void setServerIpAddress(String serverIpAddress) {
		this.serverIpAddress = serverIpAddress;
	}

	public String getServerDomainName() {
		return this.serverDomainName;
	}

	public void setServerDomainName(String serverDomainName) {
		this.serverDomainName = serverDomainName;
	}

	public BigDecimal getServerLattitude() {
		return this.serverLattitude;
	}

	public void setServerLattitude(BigDecimal serverLattitude) {
		this.serverLattitude = serverLattitude;
	}

	public BigDecimal getServerLongitude() {
		return this.serverLongitude;
	}

	public void setServerLongitude(BigDecimal serverLongitude) {
		this.serverLongitude = serverLongitude;
	}

	public String getServerCity() {
		return this.serverCity;
	}

	public void setServerCity(String serverCity) {
		this.serverCity = serverCity;
	}

	public String getServerCountry() {
		return this.serverCountry;
	}

	public void setServerCountry(String serverCountry) {
		this.serverCountry = serverCountry;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

}
